### ISSUE TITLE
gir restart as always

### ISSUE THREAD

**Issue by leonpano2006** [DiscordGIR/GIRRewrite#5]
```
gir  | [*] Ban appeals monitoring is DISABLED!
gir  | [*] Discord webhook logging is ENABLED!
gir  | [?] (m:'config', l:55) `/memegen aitext` will not be enabled.
gir  | [?] (m:'config', l:60) Markov is DISABLED! `/memegen text` features will not be enabled.
gir  | [*] GIR will be running in: 861497413298946070 in PRODUCTION mode
gir  | [*] Bot owned by: 163496482748628992
gir  | [*] Starting database...
gir  | [*] Database connected and loaded successfully!
gir  | Traceback (most recent call last):
gir  |   File "/usr/src/app/main.py", line 9, in <module>
gir  |     from utils import cfg, db, logger, GIRContext, BanCache, IssueCache, Tasks, RuleCache, init_client_session, scam_cache
gir  |   File "/usr/src/app/utils/__init__.py", line 3, in <module>
gir  |     from .database import *
gir  |   File "/usr/src/app/utils/database.py", line 22, in <module>
gir  |     db = Database()
gir  |   File "/usr/src/app/utils/database.py", line 18, in __init__
gir  |     if not Guild.objects(_id=cfg.guild_id):
gir  |   File "/opt/venv/lib/python3.10/site-packages/mongoengine/queryset/manager.py", line 38, in __get__
gir  |     queryset = queryset_class(owner, owner._get_collection())
gir  |   File "/opt/venv/lib/python3.10/site-packages/mongoengine/document.py", line 223, in _get_collection
gir  |     if cls._meta.get("auto_create_index", True) and db.client.is_primary:
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1088, in is_primary
gir  |     return self._server_property('is_writable')
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 889, in _server_property
gir  |     server = self._topology.select_server(
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 244, in select_server
gir  |     return random.choice(self.select_servers(selector,
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 202, in select_servers
gir  |     server_descriptions = self._select_servers_loop(
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
gir  |     raise ServerSelectionTimeoutError(
gir  | pymongo.errors.ServerSelectionTimeoutError: host.docker.internal
gir  | :27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 62a21e6ad2753e0af9abd918, topology_type: Single, servers: [<ServerDescription ('host.docker.internal\n', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal\n:27017: [Errno -2] Name or service not known')>]>
gir  | [*] Ban appeals monitoring is DISABLED!
gir  | [*] Discord webhook logging is ENABLED!
gir  | [?] (m:'config', l:55) `/memegen aitext` will not be enabled.
gir  | [?] (m:'config', l:60) Markov is DISABLED! `/memegen text` features will not be enabled.
gir  | [*] GIR will be running in: 861497413298946070 in PRODUCTION mode
gir  | [*] Bot owned by: 163496482748628992
gir  | [*] Starting database...
gir  | [*] Database connected and loaded successfully!
gir  | Traceback (most recent call last):
gir  |   File "/usr/src/app/main.py", line 9, in <module>
gir  |     from utils import cfg, db, logger, GIRContext, BanCache, IssueCache, Tasks, RuleCache, init_client_session, scam_cache
gir  |   File "/usr/src/app/utils/__init__.py", line 3, in <module>
gir  |     from .database import *
gir  |   File "/usr/src/app/utils/database.py", line 22, in <module>
gir  |     db = Database()
gir  |   File "/usr/src/app/utils/database.py", line 18, in __init__
gir  |     if not Guild.objects(_id=cfg.guild_id):
gir  |   File "/opt/venv/lib/python3.10/site-packages/mongoengine/queryset/manager.py", line 38, in __get__
gir  |     queryset = queryset_class(owner, owner._get_collection())
gir  |   File "/opt/venv/lib/python3.10/site-packages/mongoengine/document.py", line 223, in _get_collection
gir  |     if cls._meta.get("auto_create_index", True) and db.client.is_primary:
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1088, in is_primary
gir  |     return self._server_property('is_writable')
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 889, in _server_property
gir  |     server = self._topology.select_server(
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 244, in select_server
gir  |     return random.choice(self.select_servers(selector,
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 202, in select_servers
gir  |     server_descriptions = self._select_servers_loop(
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
gir  |     raise ServerSelectionTimeoutError(
gir  | pymongo.errors.ServerSelectionTimeoutError: host.docker.internal
gir  | :27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 62a21e8993069b0f0f4b9710, topology_type: Single, servers: [<ServerDescription ('host.docker.internal\n', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal\n:27017: [Errno -2] Name or service not known')>]>
gir  | [*] Ban appeals monitoring is DISABLED!
gir  | [*] Discord webhook logging is ENABLED!
gir  | [?] (m:'config', l:55) `/memegen aitext` will not be enabled.
gir  | [?] (m:'config', l:60) Markov is DISABLED! `/memegen text` features will not be enabled.
gir  | [*] GIR will be running in: 861497413298946070 in PRODUCTION mode
gir  | [*] Bot owned by: 163496482748628992
gir  | [*] Starting database...
gir  | [*] Database connected and loaded successfully!
gir  | Traceback (most recent call last):
gir  |   File "/usr/src/app/main.py", line 9, in <module>
gir  |     from utils import cfg, db, logger, GIRContext, BanCache, IssueCache, Tasks, RuleCache, init_client_session, scam_cache
gir  |   File "/usr/src/app/utils/__init__.py", line 3, in <module>
gir  |     from .database import *
gir  |   File "/usr/src/app/utils/database.py", line 22, in <module>
gir  |     db = Database()
gir  |   File "/usr/src/app/utils/database.py", line 18, in __init__
gir  |     if not Guild.objects(_id=cfg.guild_id):
gir  |   File "/opt/venv/lib/python3.10/site-packages/mongoengine/queryset/manager.py", line 38, in __get__
gir  |     queryset = queryset_class(owner, owner._get_collection())
gir  |   File "/opt/venv/lib/python3.10/site-packages/mongoengine/document.py", line 223, in _get_collection
gir  |     if cls._meta.get("auto_create_index", True) and db.client.is_primary:
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1088, in is_primary
gir  |     return self._server_property('is_writable')
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 889, in _server_property
gir  |     server = self._topology.select_server(
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 244, in select_server
gir  |     return random.choice(self.select_servers(selector,
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 202, in select_servers
gir  |     server_descriptions = self._select_servers_loop(
gir  |   File "/opt/venv/lib/python3.10/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
gir  |     raise ServerSelectionTimeoutError(
gir  | pymongo.errors.ServerSelectionTimeoutError: host.docker.internal
gir  | :27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 62a21ea818ca940d7ad7b4da, topology_type: Single, servers: [<ServerDescription ('host.docker.internal\n', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal\n:27017: [Errno -2] Name or service not known')>]>```

**Comment by leonpano2006** [comment]
my mistake
