### ISSUE TITLE
README.md missing documention and stuck at `gir | Exception: The database has not been set up for guild 861497413298946070! Please refer to README.md.`

### ISSUE THREAD

**Issue by leonpano2006** [DiscordGIR/GIRRewrite#6]
```
gir  | [*] Ban appeals monitoring is DISABLED!
gir  | [*] Discord webhook logging is ENABLED!
gir  | [?] (m:'config', l:55) `/memegen aitext` will not be enabled.
gir  | [?] (m:'config', l:60) Markov is DISABLED! `/memegen text` features will not be enabled.
gir  | [*] GIR will be running in: 861497413298946070 in PRODUCTION mode
gir  | [*] Bot owned by: 163496482748628992
gir  | [*] Starting database...
gir  | [*] Database connected and loaded successfully!
gir  | Traceback (most recent call last):
gir  |   File "/usr/src/app/main.py", line 9, in <module>
gir  |     from utils import cfg, db, logger, GIRContext, BanCache, IssueCache, Tasks, RuleCache, init_client_session, scam_cache
gir  |   File "/usr/src/app/utils/__init__.py", line 3, in <module>
gir  |     from .database import *
gir  |   File "/usr/src/app/utils/database.py", line 22, in <module>
gir  |     db = Database()
gir  |   File "/usr/src/app/utils/database.py", line 19, in __init__
gir  |     raise Exception(f"The database has not been set up for guild {cfg.guild_id}! Please refer to README.md.")
gir  | Exception: The database has not been set up for guild 861497413298946070! Please refer to README.md.```
then loop

**Comment by leonpano2006** [comment]
>Please refer to README.md

where should i see in README.md? it doesn't say anything about guild_id

**Comment by SlimShadyIAm** [comment]
https://github.com/DiscordGIR/GIRRewrite#database-setup
