### ISSUE TITLE
restart loop

### ISSUE THREAD

**Issue by leonpano2006** [DiscordGIR/GIRRewrite#7]
gir | discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

gir | [?] (m:'config', l:69) .env file does not have key AARON_ROLE. Some features may not function as intended.

gir | [*] Ban appeals monitoring is DISABLED!

gir | [*] Discord webhook logging is DISABLED!

gir | [?] (m:'config', l:55) `/memegen aitext` will not be enabled.

gir | [?] (m:'config', l:60) Markov is DISABLED! `/memegen text` features will not be enabled.

gir | [*] GIR will be running in: 861497413298946070 in PRODUCTION mode

gir | [*] Bot owned by: 163496482748628992

gir | [*] Starting database...

gir | [*] Database connected and loaded successfully!

gir | [?] (m:'client', l:246) PyNaCl is not installed, voice will NOT be supported

gir | [*] Presetup phase completed! Connecting to Discord...

gir | [*] logging in using static token

gir | [?] (m:'sabbath', l:44) Aaron's ID or role not set, disabling the Sabbath cog! If you want this, refer to README.md.

gir | [?] (m:'jailbreak_monitors', l:161) Pastee token not set, not loading the TweakList cog! If you want this, refer to README.md.

gir | [*] Scheduler started

gir | [*] Shard ID None has sent the IDENTIFY payload.

gir | [*] Shard ID None session has been invalidated.

gir | [*] Got a request to IDENTIFY the websocket.

gir | [*] Shard ID None has sent the IDENTIFY payload.

gir | [*] Websocket closed with 4014, cannot reconnect.

gir | Unclosed client session

gir | client_session: <aiohttp.client.ClientSession object at 0x7f53470a3550>

gir | Traceback (most recent call last):

gir |   File "/usr/src/app/main.py", line 169, in <module>

gir |     asyncio.run(main())

gir |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run

gir |     return loop.run_until_complete(main)

gir |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete

gir |     return future.result()

gir |   File "/usr/src/app/main.py", line 167, in main

gir |     await bot.start(os.environ.get("GIR_TOKEN"), reconnect=True)

gir |   File "/opt/venv/lib/python3.10/site-packages/discord/client.py", line 682, in start

gir |     await self.connect(reconnect=reconnect)

gir |   File "/opt/venv/lib/python3.10/site-packages/discord/client.py", line 619, in connect

**Comment by leonpano2006** [comment]
My mistake again
